In [1]:
import numpy as np

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[0])

1


In [4]:
arr_2d = np.array([
                    [1, 2, 3],
                    [4, 5, 7],
                    [6, 8, 9],
                    [11, 17, 19]
])

In [8]:
print(arr_2d[0,0])
print(arr_2d[-4, -3])
print(arr_2d[2, 1])

1
1
8


In [10]:
arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d[0:2])
print(arr_1d[:])

[1 2]
[1 2 3 4 5]


In [16]:
arr_2d = np.array([
                    [1, 2, 3, 5],
                    [1, 3, 5, 7],
                    [2, 4, 6, 8],
                    [7, 11, 13, 17]
                ])

# print(arr_2d[0:4])
print(arr_2d[0:4, 0])
print(arr_2d[0:3, 1])
print(arr_2d[:4, 0])

[1 1 2 7]
[2 3 4]
[1 1 2 7]


In [20]:
print(arr_2d[0:3, 0:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [21]:
print(arr_2d[1:3, :])

[[1 3 5 7]
 [2 4 6 8]]


In [22]:
arr = np.array([0, 1, -4, -16, 25])
arr_abs = np.abs(arr)
print(arr_abs)

[ 0  1  4 16 25]


In [23]:
arr_fabs = np.fabs(arr)
print(arr_fabs)

[ 0.  1.  4. 16. 25.]


In [25]:
arr_sqrt = np.sqrt(arr)
print(arr)
print(arr_sqrt)

[  0   1  -4 -16  25]
[ 0.  1. nan nan  5.]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_8144\1085780605.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr_sqrt = np.sqrt(arr)


In [26]:
arr_square = np.square(arr)
print(arr)
print(arr_square)

[  0   1  -4 -16  25]
[  0   1  16 256 625]


In [28]:
arr_exp = np.exp(arr)
print(arr_exp)

[1.00000000e+00 2.71828183e+00 1.83156389e-02 1.12535175e-07
 7.20048993e+10]


In [32]:
arr_log10 = np.log10(arr)
print(arr_log10)

[      -inf 0.                nan        nan 1.39794001]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_8144\1165559106.py:1: RuntimeWarning: divide by zero encountered in log10
  arr_log10 = np.log10(arr)
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_8144\1165559106.py:1: RuntimeWarning: invalid value encountered in log10
  arr_log10 = np.log10(arr)


In [34]:
arr_sign = np.sign(arr)
print(arr_sign)

[ 0  1 -1 -1  1]


In [36]:
arr = np.array([1.15, -2.33, 3.457, -4.095])
arr_round = np.round(arr)
print(arr_round)

[ 1. -2.  3. -4.]


In [37]:
arr_round_1 = np.round(arr, 1)
print(arr_round_1)

[ 1.2 -2.3  3.5 -4.1]


In [38]:
arr_round_c = np.ceil(arr)
print(arr_round_c)

[ 2. -2.  4. -4.]


In [39]:
arr_floor = np.floor(arr)
print(arr_floor)

[ 1. -3.  3. -5.]


In [40]:
arr_trunc = np.trunc(arr)
print(arr_trunc)

[ 1. -2.  3. -4.]


In [42]:
arr_1 = np.arange(5)
arr_1

array([0, 1, 2, 3, 4])

In [43]:
arr_2 = np.arange(1, 10, step = 2)
print(arr_2)

[1 3 5 7 9]


In [45]:
arr_add_1 = np.add(arr_1, arr_2) #각 요소끼리 연산
print(arr_add_1)

[ 1  4  7 10 13]


In [46]:
arr_add_2 = arr_1 + arr_2
print(arr_add_2)

[ 1  4  7 10 13]


In [47]:
arr_subtract_1 = np.subtract(arr_1, arr_2)
print(arr_subtract_1)

[-1 -2 -3 -4 -5]


In [48]:
arr_1 - arr_2

array([-1, -2, -3, -4, -5])

In [49]:
arr_mul = np.multiply(arr_1, arr_2)
arr_mul

array([ 0,  3, 10, 21, 36])

In [50]:
arr_divide = np.divide(arr_1, arr_2)
arr_divide

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [51]:
arr_1 / arr_2

array([0.        , 0.33333333, 0.4       , 0.42857143, 0.44444444])

In [52]:
arr_mod = np.mod(arr_1, arr_2)
arr_mod

array([0, 1, 2, 3, 4])

In [53]:
arr_1 % arr_2

array([0, 1, 2, 3, 4])

In [54]:
np.power(arr_1, arr_2)

array([     0,      1,     32,   2187, 262144])

In [55]:
arr_1 ** arr_2

array([     0,      1,     32,   2187, 262144])

In [59]:
arr_1d_3 = np.array([1, 2, 3])
print(arr_1d_3)
print(arr_1d_3.shape)

[1 2 3]
(3,)


In [60]:
arr_1d_1 = np.array([5])
print(arr_1d_1)
print(arr_1d_1.shape)

[5]
(1,)


In [61]:
arr_add = arr_1d_3 + arr_1d_1
print(arr_add)

[6 7 8]


In [62]:
arr_2d_3x3 = np.array([
                        [1, 4, 7],
                        [2, 5, 6],
                        [3, 6, 9]
                    ])
arr_2d_3x3

array([[1, 4, 7],
       [2, 5, 6],
       [3, 6, 9]])

In [63]:
arr_1d_3 = np.array([1, 0, -1])
arr_1d_3

array([ 1,  0, -1])

In [64]:
arr_add = arr_2d_3x3 + arr_1d_3
print(arr_add)

[[2 4 6]
 [3 5 5]
 [4 6 8]]


In [66]:
arr_2d_1x3 = np.array([[1, 2, 3]])
print(arr_2d_1x3)
print(arr_2d_1x3.shape) #1행 3열
print(arr_2d_1x3.ndim) #2차원

[[1 2 3]]
(1, 3)
2


In [68]:
arr_2d_3x1 = np.array([
                        [1],
                        [0],
                        [-1]
                    ])
print(arr_2d_3x1)
print(arr_2d_3x1.shape)
print(arr_2d_3x1.ndim)

[[ 1]
 [ 0]
 [-1]]
(3, 1)
2


In [70]:
arr_2d_arr = arr_2d_1x3 + arr_2d_3x1
print(arr_2d_arr)

[[2 3 4]
 [1 2 3]
 [0 1 2]]
