In [1]:
a = [
    [1, 2, 3],
    [4, 5, 6]
    ]

a[1]

[4, 5, 6]

In [3]:
# NumPy install
!pip install numpy

     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 110.1 kB/s eta 0:00:01
     ------------- ------------------------ 20.5/59.7 kB 110.1 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/59.7 kB 146.3 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/59.7 kB 187.9 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 211.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 5.5 MB/s eta 0:00:03
   - -------------------------------------- 0.3/12.6 MB 4.2 MB/s eta 0:00:03
   - -------------------------------------- 0.6/12.6 MB 4.8 MB/s eta 0:00:03
   -- ------------------------------------- 0.9/12.6 MB 5.2 MB/s eta 0:00:03
   --


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy

a = [1, 2, 3, 4, 5, 6]
print("a: ", a)
print(type(a))

b = numpy.array(a)
print("b: ", b)
print(type(b))

a:  [1, 2, 3, 4, 5, 6]
<class 'list'>
b:  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [8]:
np.array("d a t a e d u")

array('d a t a e d u', dtype='<U13')

In [9]:
np.arange(7) #range(7)

array([0, 1, 2, 3, 4, 5, 6])

In [15]:
print(range(7))
print(list(range(7)))

range(0, 7)
[0, 1, 2, 3, 4, 5, 6]


In [12]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [14]:
list(range(1, 6, 2)) #간격: 정수만

[1, 3, 5]

In [16]:
np.ones(5) #1차원 배열 5개

array([1., 1., 1., 1., 1.])

In [17]:
np.ones([2, 2]) #2행 2열

array([[1., 1.],
       [1., 1.]])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [20]:
np.full(5, 4).dtype

dtype('int64')

In [22]:
np.full(5, 4.).dtype

dtype('float64')

In [23]:
np.full(5, 4, dtype="float")

array([4., 4., 4., 4., 4.])

In [24]:
#2차원 배열
np.array([
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10]
])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [25]:
#3행 3열
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.ones((2, 5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.full((2, 5), 5) #2행 5열, 5로

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])